"""add fragments table

Revision ID: e11e4eab41d7
Revises: c2_hash_api_keys
Create Date: 2026-04-22 11:16:09.349289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e11e4eab41d7'
down_revision: Union[str, Sequence[str], None] = 'c2_hash_api_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('PERSON', 'PLACE', 'CREDENTIAL', 'MEMORY', 'IDEA', 'RESOURCE', 'JOURNAL', name='fragmenttype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('domains', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('text_search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(text, '') || ' ' || coalesce(summary, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fragments_domains', 'fragments', ['domains'], unique=False, postgresql_using='gin')
    op.create_index('ix_fragments_entities', 'fragments', ['entities'], unique=False, postgresql_using='gin')
    op.create_index('ix_fragments_team_created', 'fragments', ['team_id', 'created_at'], unique=False)
    op.create_index('ix_fragments_team_type', 'fragments', ['team_id', 'type'], unique=False)
    op.create_index('ix_fragments_text_search', 'fragments', ['text_search'], unique=False, postgresql_using='gin')
    op.create_index('ix_fragments_topics', 'fragments', ['topics'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fragments_topics', table_name='fragments', postgresql_using='gin')
    op.drop_index('ix_fragments_text_search', table_name='fragments', postgresql_using='gin')
    op.drop_index('ix_fragments_team_type', table_name='fragments')
    op.drop_index('ix_fragments_team_created', table_name='fragments')
    op.drop_index('ix_fragments_entities', table_name='fragments', postgresql_using='gin')
    op.drop_index('ix_fragments_domains', table_name='fragments', postgresql_using='gin')
    op.drop_table('fragments')
    # ### end Alembic commands ###
